### ISSUE TITLE
North seat wind not counted in yaku/han total

### ISSUE THREAD

**Issue by John-Johns0n** [Varantha/Mahjong-ScoringTrainer#34]
**Describe the bug**
The han count given by the app is incorrect: one of the two yakuhai sets in the hand (presumably north jikaze) is not counted

**Expected behaviour**
Han total should be four (4), and not three (3)

**Hand ID**
2011010102gm-00b9-0000-45ccb2622

**Screenshots**
[The incorrect hand in the trainer](https://i.imgur.com/8mJAhHr.png), and [the same hand in a known scoring calculator](https://i.imgur.com/Xpdjxzk.png)

**Comment by Varantha** [comment]
Hey, Thanks for logging this. 
I've removed this hand along with a few others. I've written a bit of code to test the hands against a Mahjong calculator so I'm hoping that should catch most of these :)
