### ISSUE TITLE
mobile web layout

### ISSUE THREAD

**Issue by Baggypants** [Varantha/Mahjong-ScoringTrainer#36]
**Describe the bug**
It's difficult to use on mobile browsers. I would like to train on a train. 

**Expected behaviour**
Some sort of adaption

**Screenshots**
![Screenshot_20230701-104331_Fennec](https://github.com/Varantha/Mahjong-ScoringTrainer/assets/4421419/b1962c89-5a4a-4500-a7f4-edcebaa3a7d4)

**Comment by Varantha** [comment]
Hey, 
Sorry for the delay on this one! When I made this website I never really considered the usability on mobile, I'm working on a project now (with some help) to make it work on smaller screens. 

Hoping in the next week I'll have something for you! 

Thanks for the feedback
