### ISSUE TITLE
The number fields cut the entered numbers on Firefox

### ISSUE THREAD

**Issue by gameraccoon** [Varantha/Mahjong-ScoringTrainer#40]
**Describe the bug**
On firefox the fields to enter numbers contains "up" and "down" buttons that make the field very small to see numbers longer than 3 digits.

The issue doesn't reproduce on Edge or Chrome, but reproduced on Firefox (both desktop and mobile)

**Expected behaviour**
The field is wide enough to enter values up to 5 digits and (ideally) doesn't have "up" and "down" arrows.

**Hand ID**
Any hand

**Screenshots**
![image](https://github.com/Varantha/Mahjong-ScoringTrainer/assets/24990031/2abec69a-c484-468c-8ac0-821049662c6b)

**Comment by Varantha** [comment]
Hey, thanks for raising this - I've tried a fix for it now. Give it a few minutes and try again.

**Comment by gameraccoon** [comment]
The fastest bugfix I've ever seen 😄 

The fields are displayed correctly now on both desktop and mobile Firefox.

Thanks

![image](https://github.com/Varantha/Mahjong-ScoringTrainer/assets/24990031/0fa6ce39-9b32-4681-aad4-d86f8db64d59)
