### ISSUE TITLE
Add information regarding the version of Tanyao Chu Rule used.

### ISSUE THREAD

**Issue by Dejongo** [Varantha/Mahjong-ScoringTrainer#44]
While using your little program, I ended up realizing that the ruleset used behind it (which seems to be due to Tenho) happens to be one which allows for an Open Tanyao Chu. That tends to be the exception, rather than the norm as far as I am aware, so it would be nice to have at least a mention on the page to let people know about it, so they can properly score the open hands that have it, instead of leaving the han out.

**Comment by Varantha** [comment]
Hi @Dejongo,

It is indeed Tenhou rules, all the hands are extracted from Tenhou game logs. 

I'm actually working on some documentation for the site at the moment (a quick how-to on scoring) so I'll be sure to highlight the ruleset used on there. 

Thanks for raising this, 
Varantha

**Comment by Dejongo** [comment]
Thank you for your reply. I think that would be enough to help the situation, yes. And the little documentation will help even more for those just starting to get into the game, so I think we can consider this closed afterwards.

**Comment by Varantha** [comment]
Hi @Dejongo 
Sorry for the delay. There's now a help feature which mentions this uses the Tenhou ruleset at the top. 
Hope it's enough.
Thanks for raising the issue
