### ISSUE TITLE
It would be nice if you could leave the fu blank without getting it marked wrong when it's a limit hand

### ISSUE THREAD

**Issue by travv0** [Varantha/Mahjong-ScoringTrainer#46]
When it's a limit hand, there's normally no reason to calculate the fu since you know the hand value as soon as you count the han. It would be nice if this trainer didn't make you calculate the fu for hands that don't need it.

**Comment by Varantha** [comment]
Hi @travv0 
Thanks for the suggestion. 
I've added an extra option in the top left which lets you ignore Fu calculations for limit hands. 
You will still be asked for a Fu calculation (as to not spoil the result of the han) but you can put anything in the box and it will ignore an incorrect answer.

**Comment by travv0** [comment]
Thanks!
