### ISSUE TITLE
Wrong fu explanation

### ISSUE THREAD

**Issue by Zopo** [Varantha/Mahjong-ScoringTrainer#49]
**Describe the bug**
The fu explanation shows a hand as "hand without fu" when it actually has fu, and also misses the fu of the open pon.

**Expected behaviour**
The hand should count the fu of the open pon, and should not be counted as no fu hand

**Hand ID**
2011010119gm-00a9-0000-71751b083

**Screenshots**
![73fc2ee7-2f72-4f78-ab73-19226b482727](https://github.com/user-attachments/assets/84665fe7-eb6f-4540-8768-5c55a96ab6f1)

**Comment by Varantha** [comment]
Hi @Zopo 
I get these explanations from a hand calculator from a different repo. 
That repo unfortunately is now archived and I believe I'm using the latest version of it so I would need to change quite a lot to properly fix that. 
For now, I'll just remove the hand from the trainer.
Thanks for raising your issue, appreciated!
